# Generated by Django 3.2.8 on 2021-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
