# Generated by Django 3.2.8 on 2021-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tournament_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
