# Generated by Django 3.2.8 on 2021-11-27 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasksubmission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('js', 'js')], default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
