# Generated by Django 3.2.8 on 2021-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20211127_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='language',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('js', 'js')], default='python', max_length=255),
            preserve_default=False,
        ),
    ]
