# Generated by Django 3.2.8 on 2021-11-27 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20211127_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='input_types',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='return_type',
            field=models.CharField(choices=[('linkedList', 'linkedList'), ('tree', 'tree'), ('array', 'array'), ('int', 'int'), ('str', 'str')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
